// Set to 'false' to actually modify the data
const DRY_RUN = true;

const COLLECTION_NAME = "auditRecord";

const ENTITY_TYPE_TO_CHANGES_PATH = {
    DeployableModel: new Set([
        "/associatedModels",
        "/associatedModels/associatedModel/createdDate",
        "/associatedModels/associatedModel/id",
        "/associatedModels/associatedModel/lastModifiedDate",
        "/associatedModels/associatedModel/metaData/name",
        "/associatedModels/associatedModel/storedModel/createdDate",
        "/associatedModels/associatedModel/storedModel/id",
        "/associatedModels/associatedModel/storedModel/lastModifiedDate",
        "/associatedModels/associatedModel/storedModel/modelAssets/assetId",
        "/associatedModels/associatedModel/storedModel/modelAssets/assetRole",
        "/associatedModels/associatedModel/storedModel/modelAssets/fileContent",
        "/associatedModels/associatedModel/storedModel/modelAssets/fileContentString",
        "/associatedModels/associatedModel/storedModel/modelAssets/fileSize",
        "/associatedModels/associatedModel/storedModel/modelAssets/importedRepository/importDirectory",
        "/associatedModels/associatedModel/storedModel/modelAssets/initFunction",
        "/associatedModels/associatedModel/storedModel/modelAssets/metricsFunction",
        "/associatedModels/associatedModel/storedModel/modelAssets/name",
        "/associatedModels/associatedModel/storedModel/modelAssets/primaryModelSource",
        "/associatedModels/associatedModel/storedModel/modelAssets/repositoryInfo/importDirectory",
        "/associatedModels/associatedModel/storedModel/modelAssets/sourceCode",
        "/associatedModels/associatedModel/storedModel/modelAssets/sourceCodeFilePath",
        "/associatedModels/associatedModel/storedModel/modelMetaData/defaultAssociationRole",
        "/associatedModels/associatedModel/storedModel/modelMetaData/description",
        "/associatedModels/associatedModel/storedModel/modelMetaData/name",
        "/associatedModels/associatedModel/storedModel/modelMetaData/repositoryInfo/importDirectory",
        "/associatedModels/associatedModel/storedModel/requiredAssets",
        "/associatedModels/associatedModel/storedModel/requiredAssets/assetId",
        "/associatedModels/associatedModel/storedModel/requiredAssets/assetRole",
        "/associatedModels/associatedModel/storedModel/requiredAssets/metaData/description",
        "/associatedModels/associationAssets",
        "/associatedModels/associationAssets/assetId",
        "/associatedModels/associationAssets/assetRole",
        "/associatedModels/associationAssets/browserUrl",
        "/associatedModels/associationAssets/contentHash/hexString",
        "/associatedModels/associationAssets/createdDate",
        "/associatedModels/associationAssets/filename",
        "/associatedModels/associationAssets/fileSize",
        "/associatedModels/associationAssets/fileUrl",
        "/associatedModels/associationAssets/metaData/description",
        "/associatedModels/associationAssets/name",
        "/associatedModels/associationRole",
        "/associatedModels/inlineAssociatedModel/createdDate",
        "/associatedModels/inlineAssociatedModel/id",
        "/associatedModels/inlineAssociatedModel/lastModifiedDate",
        "/associatedModels/inlineAssociatedModel/metaData/name",
        "/associatedModels/inlineAssociatedModel/storedModel/createdDate",
        "/associatedModels/inlineAssociatedModel/storedModel/id",
        "/associatedModels/inlineAssociatedModel/storedModel/lastModifiedDate",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/assetId",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/assetRole",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/fileContent",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/fileContentString",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/fileSize",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/importedRepository/importDirectory",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/initFunction",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/metricsFunction",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/name",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/primaryModelSource",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/repositoryInfo/importDirectory",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/sourceCode",
        "/associatedModels/inlineAssociatedModel/storedModel/modelAssets/sourceCodeFilePath",
        "/associatedModels/inlineAssociatedModel/storedModel/modelMetaData/defaultAssociationRole",
        "/associatedModels/inlineAssociatedModel/storedModel/modelMetaData/description",
        "/associatedModels/inlineAssociatedModel/storedModel/modelMetaData/name",
        "/associatedModels/inlineAssociatedModel/storedModel/modelMetaData/repositoryInfo/importDirectory",
        "/associatedModels/inlineAssociatedModel/storedModel/requiredAssets",
        "/associatedModels/inlineAssociatedModel/storedModel/requiredAssets/assetId",
        "/associatedModels/inlineAssociatedModel/storedModel/requiredAssets/assetRole",
        "/associatedModels/inlineAssociatedModel/storedModel/requiredAssets/metaData/description",
        "/associatedModels/schedules",
        "/associatedModels/schedules/scheduleId",
        "/modelDocuments",
        "/targetRuntimes/repositoryInfo/lastEndpointConfigSyncDate",
        "/targetRuntimes/repositoryInfo/lastEndpointSyncDate",
        "/targetRuntimes/repositoryInfo/lastTransformJobSyncDate"
    ]),

    DeployedModel: new Set([
        "/additionalAssets",
        "/engine/lastActivity/date",
        "/engine/lastActivity/type",
        "/engine/lastModifiedBy",
        "/engine/lastModifiedDate",
        "/engine/repositoryInfo/lastEndpointConfigSyncDate",
        "/engine/repositoryInfo/lastEndpointSyncDate",
        "/engine/repositoryInfo/lastTransformJobSyncDate",
        "/engine/state",
        "/engine/version",
        "/engine/versionNumber",
        "/schedules",
        "/schedules/action/signalVariables/SNAPSHOTS_TO_INCLUDE",
        "/schedules/cronExpression",
        "/schedules/metaData/name",
        "/schedules/scheduleId",
        "/undeployTime"
    ]),

    EngineNotification: new Set([
        "/createdBy",
        "/createdDate",
        "/engineId",
        "/lastModifiedBy",
        "/lastModifiedDate",
        "/message",
        "/severity",
        "/version",
        "/versionNumber"
    ]),

    JobNotification: new Set([
        "/createdBy",
        "/createdDate",
        "/deployableModelId",
        "/jobId",
        "/lastModifiedBy",
        "/lastModifiedDate",
        "/message",
        "/severity",
        "/storedModelId",
        "/version",
        "/versionNumber"
    ]),

    ModelApprovalNotification: new Set([
        "/approvalType",
        "/approver",
        "/assignment",
        "/assignment/closedBy",
        "/assignment/currentStatus",
        "/assignment/issueId",
        "/assignment/issueLink",
        "/assignment/jiraCurrentStatus",
        "/assignment/jiraIssue",
        "/assignment/jiraIssue/fields/attachment",
        "/assignment/jiraIssue/fields/customfield_10000",
        "/assignment/jiraIssue/fields/duedate",
        "/assignment/jiraIssue/fields/lastViewed",
        "/assignment/jiraIssue/fields/resolution",
        "/assignment/jiraIssue/fields/resolutiondate",
        "/assignment/jiraIssue/fields/status/id",
        "/assignment/jiraIssue/fields/status/name",
        "/assignment/jiraIssue/fields/status/self",
        "/assignment/jiraIssue/fields/status/statusCategory/colorName",
        "/assignment/jiraIssue/fields/status/statusCategory/id",
        "/assignment/jiraIssue/fields/status/statusCategory/key",
        "/assignment/jiraIssue/fields/status/statusCategory/name",
        "/assignment/jiraIssue/fields/status/statusCategory/self",
        "/assignment/jiraIssue/fields/updated",
        "/assignment/jiraIssueKey",
        "/assignment/jiraIssueLink",
        "/assignment/jiraIssueObject",
        "/assignment/jiraIssueObject/Archived",
        "/assignment/jiraIssueObject/Archiver",
        "/assignment/jiraIssueObject/Assignee",
        "/assignment/jiraIssueObject/Attachment",
        "/assignment/jiraIssueObject/Development",
        "/assignment/jiraIssueObject/Due Date",
        "/assignment/jiraIssueObject/Environment",
        "/assignment/jiraIssueObject/Epic Link",
        "/assignment/jiraIssueObject/Expiration Date",
        "/assignment/jiraIssueObject/Last Viewed",
        "/assignment/jiraIssueObject/Original Estimate",
        "/assignment/jiraIssueObject/Remaining Estimate",
        "/assignment/jiraIssueObject/Resolution",
        "/assignment/jiraIssueObject/Resolved",
        "/assignment/jiraIssueObject/Sprint",
        "/assignment/jiraIssueObject/Status",
        "/assignment/jiraIssueObject/Time Spent",
        "/assignment/jiraIssueObject/Update Date",
        "/assignment/jiraIssueObject/Updated",
        "/assignment/jiraIssueObject/Σ Original Estimate",
        "/assignment/jiraIssueObject/Σ Remaining Estimate",
        "/assignment/jiraIssueObject/Σ Time Spent",
        "/assignment/priority",
        "/createdBy",
        "/createdDate",
        "/deployableModelId",
        "/elevatedPriority",
        "/lastModifiedBy",
        "/lastModifiedDate",
        "/message",
        "/open",
        "/severity",
        "/storedModelId",
        "/subType",
        "/version",
        "/versionNumber"
    ]),

    ModelNotification: new Set([
        "/assignment",
        "/assignment/closedBy",
        "/assignment/currentStatus",
        "/assignment/issueId",
        "/assignment/issueLink",
        "/assignment/jiraCurrentStatus",
        "/assignment/jiraIssue",
        "/assignment/jiraIssue/fields/customfield_10000",
        "/assignment/jiraIssue/fields/customfield_10107/id",
        "/assignment/jiraIssue/fields/customfield_10107/self",
        "/assignment/jiraIssue/fields/customfield_10107/value",
        "/assignment/jiraIssue/fields/duedate",
        "/assignment/jiraIssue/fields/lastViewed",
        "/assignment/jiraIssue/fields/resolution",
        "/assignment/jiraIssue/fields/resolutiondate",
        "/assignment/jiraIssue/fields/status/iconUrl",
        "/assignment/jiraIssue/fields/status/id",
        "/assignment/jiraIssue/fields/status/name",
        "/assignment/jiraIssue/fields/status/self",
        "/assignment/jiraIssue/fields/status/statusCategory/colorName",
        "/assignment/jiraIssue/fields/status/statusCategory/id",
        "/assignment/jiraIssue/fields/status/statusCategory/key",
        "/assignment/jiraIssue/fields/status/statusCategory/name",
        "/assignment/jiraIssue/fields/status/statusCategory/self",
        "/assignment/jiraIssue/fields/updated",
        "/assignment/jiraIssueKey",
        "/assignment/jiraIssueLink",
        "/assignment/jiraIssueObject",
        "/assignment/jiraIssueObject/Archived",
        "/assignment/jiraIssueObject/Archiver",
        "/assignment/jiraIssueObject/Assignee",
        "/assignment/jiraIssueObject/Development",
        "/assignment/jiraIssueObject/Due Date",
        "/assignment/jiraIssueObject/Environment",
        "/assignment/jiraIssueObject/Epic Link",
        "/assignment/jiraIssueObject/Expiration Date",
        "/assignment/jiraIssueObject/Last Viewed",
        "/assignment/jiraIssueObject/Model Risk",
        "/assignment/jiraIssueObject/Original Estimate",
        "/assignment/jiraIssueObject/Remaining Estimate",
        "/assignment/jiraIssueObject/Resolution",
        "/assignment/jiraIssueObject/Resolved",
        "/assignment/jiraIssueObject/Sprint",
        "/assignment/jiraIssueObject/Status",
        "/assignment/jiraIssueObject/Time Spent",
        "/assignment/jiraIssueObject/Update Date",
        "/assignment/jiraIssueObject/Updated",
        "/assignment/jiraIssueObject/Σ Original Estimate",
        "/assignment/jiraIssueObject/Σ Remaining Estimate",
        "/assignment/jiraIssueObject/Σ Time Spent",
        "/assignment/priority",
        "/documentation",
        "/elevatedPriority",
        "/open"
    ]),

    ModelReviewNotification: new Set([
        "/assignment/closedBy",
        "/assignment/currentStatus",
        "/assignment/issueId",
        "/assignment/issueLink",
        "/assignment/jiraIssue/fields/customfield_10000",
        "/assignment/jiraIssueObject/Development",
        "/assignment/serviceNowCurrentStatus",
        "/assignment/serviceNowIssue",
        "/assignment/serviceNowIssue/active/display_value",
        "/assignment/serviceNowIssue/active/value",
        "/assignment/serviceNowIssue/approval_history/display_value",
        "/assignment/serviceNowIssue/approval_set/display_value",
        "/assignment/serviceNowIssue/approval_set/value",
        "/assignment/serviceNowIssue/approval/display_value",
        "/assignment/serviceNowIssue/approval/value",
        "/assignment/serviceNowIssue/assignment_group/display_value",
        "/assignment/serviceNowIssue/assignment_group/link",
        "/assignment/serviceNowIssue/assignment_group/value",
        "/assignment/serviceNowIssue/close_code/display_value",
        "/assignment/serviceNowIssue/close_code/value",
        "/assignment/serviceNowIssue/close_notes/display_value",
        "/assignment/serviceNowIssue/close_notes/value",
        "/assignment/serviceNowIssue/closed_at/display_value",
        "/assignment/serviceNowIssue/closed_at/value",
        "/assignment/serviceNowIssue/closed_by/display_value",
        "/assignment/serviceNowIssue/closed_by/link",
        "/assignment/serviceNowIssue/closed_by/value",
        "/assignment/serviceNowIssue/due_date/display_value",
        "/assignment/serviceNowIssue/due_date/value",
        "/assignment/serviceNowIssue/end_date/display_value",
        "/assignment/serviceNowIssue/end_date/value",
        "/assignment/serviceNowIssue/reassignment_count/display_value",
        "/assignment/serviceNowIssue/reassignment_count/value",
        "/assignment/serviceNowIssue/start_date/display_value",
        "/assignment/serviceNowIssue/start_date/value",
        "/assignment/serviceNowIssue/state/display_value",
        "/assignment/serviceNowIssue/state/value",
        "/assignment/serviceNowIssue/sys_mod_count/display_value",
        "/assignment/serviceNowIssue/sys_mod_count/value",
        "/assignment/serviceNowIssue/sys_updated_by/display_value",
        "/assignment/serviceNowIssue/sys_updated_by/value",
        "/assignment/serviceNowIssue/sys_updated_on/display_value",
        "/assignment/serviceNowIssue/sys_updated_on/value",
        "/assignment/serviceNowIssue/work_end/display_value",
        "/assignment/serviceNowIssue/work_end/value",
        "/assignment/serviceNowIssue/work_start/display_value",
        "/assignment/serviceNowIssue/work_start/value",
        "/assignment/serviceNowLink",
        "/assignment/serviceNowNumber",
        "/assignment/serviceNowSysId",
        "/createdBy",
        "/createdDate",
        "/deployableModelId",
        "/lastModifiedBy",
        "/lastModifiedDate",
        "/message",
        "/modelTestResults",
        "/open",
        "/severity",
        "/storedModelId",
        "/version",
        "/versionNumber"
    ]),

    ProcessNotification: new Set([
        "/assignment",
        "/assignment/currentStatus",
        "/assignment/issueId",
        "/assignment/issueLink",
        "/assignment/jiraCurrentStatus",
        "/assignment/jiraIssue",
        "/assignment/jiraIssue/fields/customfield_10000",
        "/assignment/jiraIssueKey",
        "/assignment/jiraIssueLink",
        "/assignment/jiraIssueObject",
        "/assignment/jiraIssueObject/Archived",
        "/assignment/jiraIssueObject/Archiver",
        "/assignment/jiraIssueObject/Assignee",
        "/assignment/jiraIssueObject/Development",
        "/assignment/jiraIssueObject/Due Date",
        "/assignment/jiraIssueObject/Environment",
        "/assignment/jiraIssueObject/Epic Link",
        "/assignment/jiraIssueObject/Expiration Date",
        "/assignment/jiraIssueObject/Last Viewed",
        "/assignment/jiraIssueObject/Original Estimate",
        "/assignment/jiraIssueObject/Remaining Estimate",
        "/assignment/jiraIssueObject/Resolution",
        "/assignment/jiraIssueObject/Resolved",
        "/assignment/jiraIssueObject/Sprint",
        "/assignment/jiraIssueObject/Status",
        "/assignment/jiraIssueObject/Time Spent",
        "/assignment/jiraIssueObject/Update Date",
        "/assignment/jiraIssueObject/Σ Original Estimate",
        "/assignment/jiraIssueObject/Σ Remaining Estimate",
        "/assignment/jiraIssueObject/Σ Time Spent",
        "/assignment/priority"
    ]),

    ModelTestNotification: new Set([
        "/assignment",
        "/assignment/closedBy",
        "/assignment/currentStatus",
        "/assignment/issueId",
        "/assignment/issueLink",
        "/assignment/jiraCurrentStatus",
        "/assignment/jiraCustomFields/description",
        "/assignment/jiraIssue",
        "/assignment/jiraIssue/fields/customfield_10000",
        "/assignment/jiraIssue/fields/duedate",
        "/assignment/jiraIssue/fields/lastViewed",
        "/assignment/jiraIssue/fields/priority/iconUrl",
        "/assignment/jiraIssue/fields/priority/id",
        "/assignment/jiraIssue/fields/priority/name",
        "/assignment/jiraIssue/fields/priority/self",
        "/assignment/jiraIssue/fields/resolution",
        "/assignment/jiraIssue/fields/resolutiondate",
        "/assignment/jiraIssue/fields/status/id",
        "/assignment/jiraIssue/fields/status/name",
        "/assignment/jiraIssue/fields/status/self",
        "/assignment/jiraIssue/fields/status/statusCategory/colorName",
        "/assignment/jiraIssue/fields/status/statusCategory/id",
        "/assignment/jiraIssue/fields/status/statusCategory/key",
        "/assignment/jiraIssue/fields/status/statusCategory/name",
        "/assignment/jiraIssue/fields/status/statusCategory/self",
        "/assignment/jiraIssue/fields/updated",
        "/assignment/jiraIssueKey",
        "/assignment/jiraIssueLink",
        "/assignment/jiraIssueObject",
        "/assignment/jiraIssueObject/Archived",
        "/assignment/jiraIssueObject/Archiver",
        "/assignment/jiraIssueObject/Assignee",
        "/assignment/jiraIssueObject/Development",
        "/assignment/jiraIssueObject/Due Date",
        "/assignment/jiraIssueObject/Environment",
        "/assignment/jiraIssueObject/Epic Link",
        "/assignment/jiraIssueObject/Expiration Date",
        "/assignment/jiraIssueObject/Last Viewed",
        "/assignment/jiraIssueObject/Original Estimate",
        "/assignment/jiraIssueObject/Priority",
        "/assignment/jiraIssueObject/Remaining Estimate",
        "/assignment/jiraIssueObject/Resolution",
        "/assignment/jiraIssueObject/Resolved",
        "/assignment/jiraIssueObject/Sprint",
        "/assignment/jiraIssueObject/Status",
        "/assignment/jiraIssueObject/Time Spent",
        "/assignment/jiraIssueObject/Update Date",
        "/assignment/jiraIssueObject/Updated",
        "/assignment/jiraIssueObject/Σ Original Estimate",
        "/assignment/jiraIssueObject/Σ Remaining Estimate",
        "/assignment/jiraIssueObject/Σ Time Spent",
        "/assignment/priority",
        "/elevatedPriority",
        "/open"
    ]),

    StoredModel: new Set([
        "/gitDifferences",
        "/modelAssets/assetId",
        "/modelAssets/assetRole",
        "/modelAssets/assetType",
        "/modelAssets/browserUrl",
        "/modelAssets/contentHash",
        "/modelAssets/createdDate",
        "/modelAssets/fileContent",
        "/modelAssets/fileContentString",
        "/modelAssets/fileFormat",
        "/modelAssets/filename",
        "/modelAssets/fileSize",
        "/modelAssets/fileUrl",
        "/modelAssets/importedRepository",
        "/modelAssets/importedRepository/lastCommitDate",
        "/modelAssets/importedRepository/lastCommitId",
        "/modelAssets/importedRepository/lastSyncDate",
        "/modelAssets/importedRepository/lastSyncMessages",
        "/modelAssets/importedRepository/lastSyncStatus",
        "/modelAssets/localFile",
        "/modelAssets/name",
        "/modelAssets/parameters",
        "/modelAssets/repositoryInfo/connectionUri",
        "/modelAssets/repositoryInfo/lastCommitDate",
        "/modelAssets/repositoryInfo/lastCommitId",
        "/modelAssets/repositoryInfo/lastSuccessfulSync",
        "/modelAssets/repositoryInfo/lastSyncDate",
        "/modelAssets/repositoryInfo/lastSyncMessages",
        "/modelAssets/repositoryInfo/lastSyncStatus",
        "/modelAssets/repositoryInfo/repositoryBranch",
        "/modelAssets/repositoryInfo/repositoryDirectory",
        "/modelAssets/repositoryInfo/repositoryRemote",
        "/modelAssets/repositoryInfo/repositoryType",
        "/modelAssets/sourceCode",
        "/modelAssets/sqlStatement",
        "/useCaseIds"
    ])
 };

let deletedCount = 0;
let updatedCount = 0;
let processedCount = 0;

function normalizePath(path) {
  if (!path) return path;
  // Remove numeric indexes (middle or end)
  return path.replace(/\/\d+(?=\/|$)/g, "");
}

Object.keys(ENTITY_TYPE_TO_CHANGES_PATH).forEach(entityType => {
  const pathsToClean = ENTITY_TYPE_TO_CHANGES_PATH[entityType];

  db.getCollection(COLLECTION_NAME).find({
      entityType: entityType,
      changes: { $ne: [] }
    }).forEach(function (doc) {
      try {
        processedCount++;

        if (!doc.changes || !Array.isArray(doc.changes)) return;

        const filteredChanges = doc.changes.filter(change => {
          return !pathsToClean.has(normalizePath(change.path));
        });

        if (filteredChanges.length === 0) {
          deletedCount++;

          if (!DRY_RUN) {
            db.getCollection(COLLECTION_NAME).deleteOne({ _id: doc._id });
          }
        } else if (filteredChanges.length !== doc.changes.length) {
          updatedCount++;

          if (!DRY_RUN) {
            db.getCollection(COLLECTION_NAME).updateOne(
              { _id: doc._id },
              { $set: { changes: filteredChanges } }
            );
          }
        }
      } catch (error) {
        print("Error processing audit record " + doc._id.toString('base64') + " " + error);
      }
    });

    print("");
    print("========== SUMMARY ==========");
    print("Dry run           : " + DRY_RUN);
    print("Collection name   : " + COLLECTION_NAME);
    print("Entity type       : " + entityType);
    print("Processed records : " + processedCount);
    print("Records to update : " + updatedCount);
    print("Records to delete : " + deletedCount);
    print("=============================");
});